<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Goods Attribute Names' => '商品属性管理',
    'Create Goods Attribute Name' => '创建属性',
    'Create' => '创建',
    'Update' => '修改',
    'Update Goods Category: ' => '修改分类:',
    'Delete' => '删除',
    'Please Filter' => '请选择',
    'Batch Delete' => '批量删除',
    'Update Goods Attribute Name: ' => '修改商品属性：',
];
