<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Goods Brands' => '商品品牌管理',
    'Create Goods Brand' => '添加品牌',
    'Create' => '创建',
    'Update' => '修改',
    'Update Goods Brand: ' => '修改品牌:',
    'Delete' => '删除',
    'Please Filter' => '请选择',
];
