<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'System' => '系统相关',
	'System Setting' => '系统设置',
	'Key-Value Storage' => '键值存储',
	'Key Storage Items' => '键值存储项',
	'Create Key Storage Item' => '创建键值存储项',
	'Update Key Storage Item: ' => '修改键值存储项: ',
	'Cache' => '缓存',
	'Flush' => '清除',
	'Are you sure you want to flush this cache?' => '确定清除缓存?',
	'Delete a value with the specified key from cache' => '从缓存中删除指定键的值',
	'Invalidate tag' => '无效的标签',
    'Select cache' => '选择缓存',
    'Key' => '键',
    'Tag' => '标签',
    'TagDependency was invalidated' => '标签依赖无效',
    'Cache has been successfully flushed' => '缓存已成功刷新',
    'Given cache name is not a name of cache component' => '给定的缓存名称不是缓存组件的名称',
	'Logs' => '日志',
	'Timeline' => '动态',
	'Application timeline' => '应用动态',
	'Content' => '内容管理',
	'Hello, {username}' => '您好, {username}',
	'You have new user!' => '新用户注册!',
	'New user ({identity}) was registered at {created_at}' => '新用户 ({identity}) 于 {created_at}注册',
	'User' => '用户相关',
	'User Management' => '管理用户',
	'Create User' => '创建用户',
	'Update' => '修改',
	'Create' => '创建',
	'Save' => '保存',
	'System Logs' => '系统日志',
	'Clear' => '清空',
	'Level' => '等级',
	'Category' => '类别',
	'Log Time' => '日志记录时间',
	'Prefix' => '前缀',
	'Message' => '消息',
	'error' => '错误',
	'warning' => '警告',
	'info' => '信息',
	'trace' => '追踪',
	'profile begin' => '属性开始',
	'profile end' => '属性结束',
	'Logout' => '退出',
	'You have {num} log items' => '您有 {num} 条日志项',
	'View all' => '查看所有',
	'Application settings' => '应用设置',
	'Frontend maintenance mode' => '前端维护模式',
	'Disabled' => '禁用',
	'Enabled' => '启用',
	'Backend theme' => '后端主题',
	'Fixed backend layout' => '固定后端布局',
	'Boxed backend layout' => '盒子化后端布局',
	'Backend sidebar collapsed' => '后端侧边栏隐藏',
	'Settings was successfully saved' => '设置成功保存',
	'Articles' => '文章管理',
	'Article Categories' => '文章分类管理',
	'If you\'ll leave this field empty, slug will be generated automatically' => '如果留空，标签会自动生成',
	'Update Article: ' => '修改文章',
	'Create Article' => '创建文章',
	'Not Published' => '未发布',
	'Published' => '已发布',
	'Create Article Category' => '创建文章分类',
	'Update Article Category: ' => '修改文章分类：',
	'Error #{id}' => '错误 #{id}',
	'Delete' => '删除',
	'IT We Share Admin' => 'IT自学网管理后台',
	'Main' => '控制面板',
	'Published Time ...' => '发布时间...',
];