<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Register' => '注册',
	'Login' => '登陆',
	'Home' => '首页',
	'Language' => '语言',
	'Logout' => '退出',
	'Key' => '键',
	'Value' => '值',
	'Comment' => '说明',
	'Slug' => '标签',
	'Title' => '标题',
	'Category' => '分类',
	'Author' => '作者',
	'Published' => '发布',
	'Published At' => '发布时间',
	'Created At' => '创建时间',
	'Article View' => '文章预览次数',
	'Body' => '内容',
	'Thumbnail' => '略缩图',
	'Attachments' => '附件',
	'Active' => '激活状态',
	'Parent Category' => '父类',
	'Ok' => '确认',
	'Cancle' => '取消',
	'Are you sure to batch delete?' => '确认批量删除？',
	'Are you sure to delete ?' => '确认删除吗？',
	'Operation' => '操作',
	'View' => '查看',
	'Update' => '修改',
	'Delete' => '删除',
];