<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Parent ID' => '父类',
    'Name' => '分类名',
    'Ico' => '图标',
    'Sort' => '排序',
    'Remark' => '备注',
    'Create At' => '创建时间',
    'Create By' => '创建人',
    'Update At' => '修改时间',
    'Update By' => '修改人',
    'Status' => '状态',
    'Disabled' => '失效',
    'Enabled' => '有效',
    'Deleted' => '删除',
    'Create Person' => '创建人',
    'Updated Person' => '修改人',
];