<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Category ID' => '所属分类',
    'Name' => '属性名',
    'Is Sku Attribute' => '是否SKU属性',
    'Logo Base Url' => '',
    'Remark' => '备注',
    'Created At' => '创建时间',
    'Created By' => '创建人',
    'Updated At' => '修改时间',
    'Updated By' => '修改人',
    'Sort' => '排序',
    'Status' => '状态',
    'Disabled' => '失效',
    'Enabled' => '有效',
    'Deleted' => '删除',
    'Is Sku' => '是Sku属性',
    'Not Sku' => '不是Sku属性',
    'Category Search' => '所属分类',
    'Create Person' => '创建人',
    'Updated Person' => '修改人',
    'Attribute Name' => '属性名',
    'Attribute Value' => '属性值',
    'Ico' => '小图标',
    'Ico Path' => '小图标',
];