<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Category ID' => '所属分类',
    'Name' => '品牌名',
    'Logo' => '品牌LOGO',
    'Sort' => '排序',
    'Description' => '描述',
    'Status' => '状态',
    'Created At' => '创建时间',
    'Created By' => '创建人',
    'Updated At' => '修改时间',
    'Updated By' => '修改人',
    'Category Search' => '所属分类',
    'Create Person' => '创建人',
    'Updated Person' => '修改人',
];