<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'System' => '系统相关',
	'System Setting' => '系统设置',
	'Store Admin' => '店铺管理后台',
	'Dashboard' => '控制面板',
	'Logout' => '退出',
	'Application settings' => '应用设置',
	'Frontend maintenance mode' => '前端维护模式',
	'Disabled' => '禁用',
	'Enabled' => '启用',
	'Store theme' => '店铺主题',
	'Fixed store layout' => '固定店铺布局',
	'Boxed store layout' => '盒子化店铺布局',
	'Store sidebar collapsed' => '店铺侧边栏隐藏',
	'Settings was successfully saved' => '设置成功保存',
	'Save' => '保存',
	'Main' => '主面板',
	'Goods Management' => '商品管理',
	'Self Category Management' => '自定义分类管理',
];